import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Updated Kinetic Cyber-Dark Design Tokens
        "space-black": "#050608",
        "surface-dim": "#111318",
        "surface-bright": "#37393e",
        "surface-container-lowest": "#0c0e12",
        "surface-container-low": "#1a1c20",
        "surface-container": "#1e2024",
        "surface-container-high": "#282a2e",
        "surface-container-highest": "#333539",
        "on-surface": "#e2e2e8",
        "on-surface-variant": "#bbc9cf",
        "inverse-surface": "#e2e2e8",
        "inverse-on-surface": "#2f3035",
        "outline": "#859399",
        "outline-variant": "#3c494e",
        "surface-tint": "#47d6ff",
        "primary": "#a5e7ff",
        "on-primary": "#003543",
        "primary-container": "#00d2ff",
        "on-primary-container": "#00566a",
        "inverse-primary": "#00677f",
        "secondary": "#ecb2ff",
        "on-secondary": "#520071",
        "secondary-container": "#cf5cff",
        "on-secondary-container": "#480063",
        "tertiary": "#e5d7ff",
        "on-tertiary": "#3c0090",
        "tertiary-container": "#ccb6ff",
        "on-tertiary-container": "#6100de",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#b6ebff",
        "primary-fixed-dim": "#47d6ff",
        "on-primary-fixed": "#001f28",
        "on-primary-fixed-variant": "#004e60",
        "secondary-fixed": "#f8d8ff",
        "secondary-fixed-dim": "#ecb2ff",
        "on-secondary-fixed": "#320047",
        "on-secondary-fixed-variant": "#74009f",
        "tertiary-fixed": "#e9ddff",
        "tertiary-fixed-dim": "#d1bcff",
        "on-tertiary-fixed": "#23005b",
        "on-tertiary-fixed-variant": "#5700c9",
        "background": "#111318",
        "on-background": "#e2e2e8",
        "surface-variant": "#333539",
        "void-gray": "#1A1D23",
        "data-flow": "#00D2FF",
        "desired-state": "#BD00FF",
        "error-pulse": "#FF005C",
        "success-glow": "#00FFC2",

        // Base Aliases
        bg: "#080510",
        bg2: "#0D0A1E",
        surface: "#111318",
        raised: "#1A1430",
        line: "#2E2450",
        ink: "#F5F1FF",
        dim: "#BEB8D8",
        faint: "#6E6890",
        signal: "#3DDC97",
        magenta: "#FF3D9A",
        cyan: "#3DD6FF",
        amber: "#FFC93D",
        purple: "#B47FFF",
      },
      fontFamily: {
        mono: ["var(--font-mono)", "JetBrains Mono", "ui-monospace", "monospace"],
        sans: ["var(--font-sans)", "Geist", "ui-sans-serif", "system-ui"],
        display: ["var(--font-display)", "Geist", "ui-sans-serif", "system-ui"],
        "body-md": ["var(--font-sans)", "Geist", "sans-serif"],
        "body-lg": ["var(--font-sans)", "Geist", "sans-serif"],
        "headline-lg": ["var(--font-display)", "Geist", "sans-serif"],
        "headline-md": ["var(--font-display)", "Geist", "sans-serif"],
        "headline-lg-mobile": ["var(--font-display)", "Geist", "sans-serif"],
        "display-xl": ["var(--font-display)", "Geist", "sans-serif"],
        "technical-sm": ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "label-caps": ["var(--font-mono)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-xl": ["80px", { lineHeight: "88px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "technical-sm": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
      },
      spacing: {
        "section-gap": "120px",
        "margin-desktop": "64px",
        "base": "8px",
        "gutter": "24px",
        "margin-mobile": "16px",
      },
      keyframes: {
        pulse2: { "0%,100%": { opacity: "1" }, "50%": { opacity: "0.3" } },
        marquee: { "0%": { transform: "translateX(0)" }, "100%": { transform: "translateX(-50%)" } },
        floaty: { "0%,100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-12px)" } },
        blob: { "0%,100%": { transform: "scale(1)" }, "50%": { transform: "scale(1.08)" } },
      },
      animation: {
        pulse2: "pulse2 2s ease-in-out infinite",
        marquee: "marquee 20s linear infinite",
        floaty: "floaty 5s ease-in-out infinite",
        blob: "blob 8s ease-in-out infinite",
      },
      backgroundImage: {
        "grid-faint": "linear-gradient(to right,#ffffff04 1px,transparent 1px),linear-gradient(to bottom,#ffffff04 1px,transparent 1px)",
        hazard: "repeating-linear-gradient(45deg,#FFC93D,#FFC93D 8px,#080510 8px,#080510 16px)",
      },
      backgroundSize: { grid: "48px 48px" },
    },
  },
  plugins: [],
};
export default config;
